### PR TITLE
Changed the rotation from the camera to the image and mask

### PR DESCRIPTION
**Pull request by MickHarrigan**

### CODE REVIEW

**Comment by clostoski** [comment]
Does it need to be the image AND the mask? Should it not just be the image??

**Comment by MickHarrigan** [comment]
> Does it need to be the image AND the mask? Should it not just be the image??

if the mask is not moved then the image peeks around the mask as it rotates.

This is only a real issue when they zoom out, but that is still not a hard fix and should still be covered with this.

**Review by clostoski — APPROVED** [review]
Looks good

**Comment by MickHarrigan** [comment]
> > Does it need to be the image AND the mask? Should it not just be the image??
> 
> if the mask is not moved then the image peeks around the mask as it rotates.
> 
> This is only a real issue when they zoom out, but that is still not a hard fix and should still be covered with this.

Well, this does actually have a flaw with the mask 2, because since the mask rotates as well that makes that mask rotate of course. The issue is that the second mask isn't a circle so it rotates around a different axis.

**Pull request merged**
